version: 2
registries:
  dockerhub:
    type: "docker-registry"
    url: "https://registry.hub.docker.com/"
    username: "mark@jounce.io"
    password: "w*cRN9*DqSAbWEy"
updates:
  - package-ecosystem: "docker"
    directory: "test"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    registries:
      - dockerhub
